apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
  labels:
    app: marketplace-service
spec:
  type: ClusterIP
  selector:
    app: marketplace-service
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
