apiVersion: v1
kind: ServiceAccount
metadata:
  name: agriconnect-services
  namespace: {{ .Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.irsaRoleArn | quote }}
