apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: {{ .Values.services.order.replicas }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: agriconnect-services
      containers:
        - name: order-service
          image: {{ .Values.services.order.image }}:{{ .Values.services.order.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
              protocol: TCP
          envFrom:
            - configMapRef:
                name: agriconnect-config
          env:
            - name: PORT
              value: "3003"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
      terminationGracePeriodSeconds: 30
